os: linux
dist: focal
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
  - 3.13
  - 3.14
  - 3.14-dev
  - nightly
  - pypy3.6-7.3.3
  - pypy3.7-7.3.5
install:
    - pip install --upgrade pytest coveralls coverage
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then export TRAVIS_WAIT=45; else export TRAVIS_WAIT=20; fi
script:
  - pwd
  - coverage run --source=neat -m pytest tests
after_success:
    coveralls
