language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  - 3.8
  - 3.8-dev
  - nightly
  - pypy3
install:
    - pip install --upgrade nose coveralls coverage
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then export TRAVIS_WAIT=45; else export TRAVIS_WAIT=20; fi
script:
    travis_wait "${TRAVIS_WAIT}" nosetests --with-coverage --cover-package=neat -vd
after_success:
    coveralls
