name: neat-python-examples
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - cairo
  - graphviz
  - python-graphviz
  - matplotlib
  - pip:
      - gymnasium[box2d,mujoco]
      - gizeh
      - moviepy
      - pygame
